export const LOAD_COMMENTS = 'COMMENTS/LOAD_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'COMMENTS/LOAD_COMMENTS_SUCCESS';

export const COMMENTS_POST = 'COMMENTS/LOAD_BY_POST';
export const COMMENTS_USER = 'COMMENTS/LOAD_BY_USER';
export const COMMENTS_LOAD = 'COMMENTS/LOAD';
export const COMMENTS_SUCCESS = 'COMMENTS/SUCCESS';
export const COMMENTS_ERROR = 'COMMENTS/ERROR';
