export const LOAD_POST_SUCCESS = 'POST/LOAD_SUCCESS';
export const SHOW_LOADER = 'POST/SHOW_LOADER';
export const HIDE_LOADER = 'POST/HIDE_LOADER';

export const POSTS_USER = 'POSTS/LOAD_BY_USER';
export const POSTS_LOADING = 'POSTS/LOAD';
export const LOAD_POSTS_SUCCESS = 'POSTS/SUCCESS';
export const GET_CURRENT_POSTS_SUCCESS = 'POSTS/CET_CURRENT_POSTS_SUCCESS';
export const LOAD_POSTS_ERROR = 'POSTS/ERROR';
